$content = Get-Content -Raw -Path 'src\lib\ai\engines\confidenceCalibrator.ts'
$content = $content -replace 'policyNumber', 'policeNumarasi'
$content = $content -replace 'insuranceCompany', 'sigortaSirketi'
$content = $content -replace 'startDate', 'baslangicTarihi'
$content = $content -replace 'endDate', 'bitisTarihi'
$content = $content -replace 'premium\.totalPremium', 'primBilgileri.toplamPrim'
$content = $content -replace 'premium\.netPremium', 'primBilgileri.netPrim'
$content = $content -replace 'premium\?', 'primBilgileri?'
$content = $content -replace 'premium\.', 'primBilgileri.'
$content = $content -replace 'totalPremium', 'toplamPrim'
$content = $content -replace 'netPremium', 'netPrim'
$content = $content -replace 'policyType', 'policeTipi'
$content = $content -replace 'coverages', 'teminatlar'
$content = $content -replace 'currency', 'paraBirimi'
Set-Content -Path 'src\lib\ai\engines\confidenceCalibrator.ts' -Value $content
